region               = "us-east-1"
availability_zone_1a = "us-east-1a"
vpc_id               = "vpc-0052c4a746533c5ee"
public_subnet_1a     = "subnet-0bc0b6f570f83a70b"
instance_keypair     = "stageadmin-key"
instance_type        = "t2.micro"
instance_name        = "ubuntu-jenkins-terraform"